### ISSUE TITLE
Could you, please, make an example of sending multipart request?

### ISSUE THREAD

**Issue by streamride** [vinaysshenoy/enhanced-volley#2]
Could you, please, make an example of sending multipart request?

**Comment by vinaysshenoy** [comment]
Ah, I've been meaning to update the wiki with documentation, but I never seem to find time. Anyway, to make a MultiPart request, you'll need to use the two methods `MultiPartRequest#addMultipartParam(name, contentType, value)` and `MultiPartRequest#addFile(name, path)`.

The content type is 'application/octet-stream' for all files and is not configurable as of now. At the time of doing the request, all string params are added first, then the file params. Order is NOT maintained.

Let me know if this doesn't help you and I'll see what I can do.

Keep in mind though, that the API is not finalized, and I plan to refactor it and make it cleaner.

**Comment by streamride** [comment]
Actually, I don't understand how to use method addMultiPartParam. I mean what parameters should I add?
For example, I have to upload a photo. I'm doing like this:
<code>
MultiPartRequest<JSONObject> multiPartRequest = new MultiPartRequest<JSONObject>(Request.Method.POST, url, responseListener, errorListener) {
            @Override
            protected Response<JSONObject> parseNetworkResponse(NetworkResponse response) {
                return null;
            }
        };
        multiPartRequest.addFile("photo", filePath);
        multiPartRequest.addMultipartParam("photo", "application/octet-stream", filePath);
        queue.add(multiPartRequest);</code>

Is this right?

**Comment by vinaysshenoy** [comment]
Oh, no. The `addMultipartParam` method is for adding the string parameters of a multipart request. If you just want to upload the file, you only need the `addFile()` method.

**Comment by streamride** [comment]
Oh, thank you! So is this all? Because server return error 411 (Length required)

**Comment by vinaysshenoy** [comment]
Oh! In this case, it means that server doesn't support chunked mode transfer. Which seems pretty strange because most servers do support chunked mode transfer. Maybe it's just not enabled?

**Comment by vinaysshenoy** [comment]
And is it running on a 2.3.3 device or later?

**Comment by streamride** [comment]
On 2.3 device there is no working other requests. So, I'll try to discover it.
