### ISSUE TITLE
How using Cookies Session after sucess login api for next other datarequest?

### ISSUE THREAD

**Issue by chuquangbao** [vinaysshenoy/enhanced-volley#4]
I found many solutions in Stackover.com and many other blog. But i don't really know How.!
If In Postman i login my api success, it take a sessionid in cookies. 
After i countinue to using other api without login! But Android is not.
With your experiences, can you help me? thanks.

**Comment by ghost** [comment]
Cookies are generally best used for Web Apps. For consuming APIs, It's best if the server uses an Auth token it sends in the response body, as most APIs do. I might add in cookie support later, but it's not on the cards anytime soon. In case you do need it, you can implement it yourself. An excellent overview of Http cookies is available [here](http://www.nczonline.net/blog/2009/05/05/http-cookies-explained/).

You can look at the `HttpHeaderParser` class as a good place to implement this functionality.
